audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  format: int16
  silence_threshold: 13
  silence_duration: 2.0
  max_recording_time: 120.0

whisper:
  model: large
  language: en
  device: cuda  # cuda, cpu, or auto
  compute_type: float16  # float16, int8, or float32
  load_timeout: 60  # seconds to wait for model loading

llm:
  provider: openai  # openai or anthropic
  model: gpt-3.5-turbo
  max_tokens: 500
  default_profile: general  # default profile to use
  
  # Different prompt profiles for different contexts
  profiles:
    general:
      name: "General Text Cleanup"
      prompt: >
        Please clean up and format this transcribed text, 
        fixing any grammar issues and making it more readable 
        while preserving the original meaning:
    
    slack:
      name: "Slack Message"
      prompt: >
        Convert this transcribed speech into a professional but friendly Slack message.
        Fix grammar, make it concise, and ensure it's appropriate for workplace communication.
        Use a casual but professional tone:
    
    email:
      name: "Email"
      prompt: >
        Transform this transcribed speech into a well-structured email.
        Add proper grammar, professional tone, and clear structure.
        Make it concise but complete:
    
    todo:
      name: "Todo/Task"
      prompt: >
        Convert this speech into a clear, actionable todo item or task description.
        Make it specific, concise, and action-oriented.
        Use bullet points if multiple tasks are mentioned:
    
    obsidian:
      name: "Obsidian Note"
      prompt: >
        Format this transcribed text as a clean Obsidian markdown note.
        Fix grammar, add appropriate markdown formatting, and structure it clearly.
        Use ## headings and bullet points where appropriate:
        
    meeting_notes:
      name: "Meeting Notes"
      prompt: >
        Structure this transcribed speech as organized meeting notes.
        Use bullet points, identify action items, and make it scannable.
        Highlight important decisions and next steps:

clipboard:
  auto_paste: false
  paste_delay: 0.1

# API keys (can be overridden with environment variables)
# OPENAI_API_KEY and ANTHROPIC_API_KEY
api_keys:
  openai_api_key: ""
  anthropic_api_key: ""