audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 2048  # Increased buffer size to prevent overflow
  format: int16
  silence_threshold: 15
  silence_duration: 2.0
  max_recording_time: 120.0

whisper:
  model: large
  language: en
  device: cuda  # cuda, cpu, or auto
  compute_type: float16  # float16, int8, or float32
  load_timeout: 60  # seconds to wait for model loading

ui:
  enabled: true          # Enable/disable visual overlay
  position_x: 50         # Overlay X position on screen
  position_y: 50         # Overlay Y position on screen  
  auto_hide_delay: 3.0   # Seconds to auto-hide after completion (0 = no auto-hide)

llm:
  enabled: true             # Enable/disable LLM refinement (use raw transcription when false)
  provider: openai          # openai or anthropic
  model: gpt-3.5-turbo
  max_tokens: 500
  default_profile: general  # default profile to use
  
  # Different prompt profiles for different contexts
  profiles:
    general:
      name: "General Text Cleanup"
      prompt: >
        Please clean up and format this transcribed text, 
        fixing any grammar issues and making it more readable.
        It is extremely important to maintain the original meaning
        and not add any additional information:
    
    todo:
      name: "Todo/Task"
      prompt: >
        Convert this speech into a clear, actionable todo item or task description.
        Make it specific, concise, and action-oriented.
        Use bullet points (markdown format) if multiple tasks are mentioned:

clipboard:
  auto_paste: false
  paste_delay: 0.1

# API keys (can be overridden with environment variables)
# OPENAI_API_KEY and ANTHROPIC_API_KEY
api_keys:
  openai_api_key: ""
  anthropic_api_key: ""