api_keys:
  anthropic_api_key: ""
  openai_api_key: ""
audio:
  channels: 1
  chunk_size: 2048
  format: int16
  max_recording_time: 120.0
  sample_rate: 16000
  silence_duration: 2.0
  silence_threshold: 25
clipboard:
  auto_paste: false
  paste_delay: 0.1
llm:
  default_profile: general
  enabled: true
  max_tokens: 500
  model: gpt-3.5-turbo
  profiles:
    general:
      name: General Text Cleanup
      prompt:
        "Please clean up and format this transcribed text,  fixing any grammar
        issues and making it more readable. It is extremely important to maintain
        the original meaning and not add any additional information:

        "
    todo:
      name: Todo/Task
      prompt:
        "Convert this speech into a clear, actionable todo item or task description.
        Make it specific, concise, and action-oriented. Use bullet points (markdown
        format) if multiple tasks are mentioned:

        "
    slack:
      name: Slack Message
      prompt: 'Convert this speech into a personalized Slack message.
        I do not use capital letters to start phrases etc, but I do
        use capital "I" whenever I am refering to myself,
        i.e.: here is a slack message, I usually type in this way..

        '
  provider: openai
ui:
  auto_hide_delay: 3.0
  enabled: true
  position_x: 50
  position_y: 50
whisper:
  compute_type: float16
  device: cuda
  language: en
  load_timeout: 60
  model: turbo
