audio:
  sample_rate: 16000
  channels: 1
  chunk_size: 1024
  format: int16
  silence_threshold: 13
  silence_duration: 2.0
  max_recording_time: 120.0

whisper:
  model: large
  language: en
  device: cuda  # cuda, cpu, or auto
  compute_type: float16  # float16, int8, or float32
  load_timeout: 60  # seconds to wait for model loading

llm:
  provider: openai  # openai or anthropic
  model: gpt-3.5-turbo
  refinement_prompt: >
    Please clean up and format this transcribed text, 
    fixing any grammar issues and making it more readable 
    while preserving the original meaning:
  max_tokens: 500

clipboard:
  auto_paste: false
  paste_delay: 0.1

# API keys (can be overridden with environment variables)
# OPENAI_API_KEY and ANTHROPIC_API_KEY
api_keys:
  openai_api_key: ""
  anthropic_api_key: ""